package:
  name: chained
  version: 0.0.8

build:
  number: 1

requirements:
  build:
    - python~=3.8
    - setuptools
  run:
    - python~=3.8
about:
  summary: Making Python language more functional